image:
  file: .gitpod.Dockerfile
tasks:
  - init: ./.gitpod-init.sh || exit 1
    command: git config --global user.email $GIT_AUTHOR_EMAIL
vscode:
  extensions:
    - ms-pyright.pyright
    - magicstack.MagicPython